version: 2.0.{build}
os: Visual Studio 2017
configuration: Release

# enable version patching with build version number 
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'

# temporary workaround for getting Azure Storage Emulator 5.2 installed
install: 
  - ps: | 
       $msiPath = "$env:TEMP\MicrosoftAzureStorageEmulator.msi" 
       (New-Object Net.WebClient).DownloadFile('https://download.microsoft.com/download/F/3/8/F3857A38-D344-43B4-8E5B-2D03489909B9/MicrosoftAzureStorageEmulator.msi', $msiPath) 
       cmd /c start /wait msiexec /i $msiPath /quiet 
       del $msiPath

# restore NuGet packages before running
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore --verbosity m
  # Start the azure storage emulator
  - '"%ProgramFiles(x86)%\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe" start'


build:
 verbosity: minimal

 test_script:  
  - cd tests\TableStorage.Abstractions.Tests
  - dotnet xunit -fxversion 2.0.5