version: 1.0.{build}
os: Visual Studio 2015
configuration: Release

# enable AssemblyInfo.cs patching with build version number 
assembly_info: 
 patch: true 
 file: AssemblyInfo.* 
 assembly_version: "{version}" 
 assembly_file_version: "{version}" 
 assembly_informational_version: "{version}" 

# temporary workaround for getting Azure Storage Emulator 5.2 installed
install: 
  - ps: | 
       $msiPath = "$env:TEMP\MicrosoftAzureStorageEmulator.msi" 
       (New-Object Net.WebClient).DownloadFile('https://download.microsoft.com/download/F/3/8/F3857A38-D344-43B4-8E5B-2D03489909B9/MicrosoftAzureStorageEmulator.msi', $msiPath) 
       cmd /c start /wait msiexec /i $msiPath /quiet 
       del $msiPath

# restore NuGet packages before running MSBuild
before_build:
  - nuget restore
  - '"%ProgramFiles(x86)%\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe" start'
  
build:
 verbosity: minimal
